[package]
name = "stream"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-stream = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
