[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
axum = { workspace = true }
serde_json = { workspace = true }
protocol = { workspace = true }
tokio-stream = { workspace = true }
